# Generated by Django 4.1.1 on 2022-09-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birge_biz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifieddeliverer',
            name='telegramId',
            field=models.CharField(default='', max_length=64),
        ),
    ]
